### ISSUE TITLE
Could not fetch extension <extension-name>

### ISSUE THREAD

**Issue by bintoll** [shoutem/cli#33]
The error changes from time to time. 
Yesterday i was cloning a blank app successfully. But today i always get an error: "Could not fetch extension <extension-name>" on different extensions. If i delete this extension from builder. I do not get this error with this extensions. But there are standart extensions that i can not delete.
Also this changes the problem extension from time to time. And cli can successfully load the extension that could not load previous time.
To reproduce:
Create new app in shoutem builder.
Go to cmd and clone this newly created app.

"shoutem last-error" outputs:
`errno:   -5
code:    Z_BUF_ERROR
stack:
  """
    Error: Could not fetch extension shoutem.menu
        at Zlib._handle.onerror (zlib.js:370:17)
  """
message: Could not fetch extension shoutem.menu`

**Comment by Vladimir-Vdovic** [comment]
Usually this error is associated with network connection issues. Unstable connection, proxies, VPN, etc. We've seen this report before and there's nothing we can do to resolve it. We've tried to reduce the strain on networking by switching from parallel download to serial download (instead of 40+ extensions at the same time, we go one by one). I would suggest checking if there's any issues with your connection and/or trying with a different connection to see if that helps.

**Comment by bintoll** [comment]
Yes you are right it is because connection. I think it could be better not to abort all clone command when some of the extensions could not be fetched. And let the user to continue cloning the app. And after that write in commend line that there are problems. So the user will be able to download this extensions manually for example from github. The main idea is not to block user if he can not download some extensions.
